In [ ]:
import pandas as pd
import numpy as np
import openpyxl

In [ ]:
DADOS_GERACAO_DIARIO = pd.read_excel('C:/Users/rafae/Code/Estágio/OM_Dashboard/data-dashboard/src/data/CONTROLE DE Geração 01_2026_JANEIRO.xlsm', sheet_name='2026 P50', header=4, parse_dates=['DIA'], nrows=33)
DADOS_GERACAO_DIARIO = DADOS_GERACAO_DIARIO.drop([0,1], axis=0).reset_index(drop=['inedx'])
DADOS_GERACAO_DIARIO['DIA'] = pd.to_datetime({'year': 2026, 'month': 1, 'day': DADOS_GERACAO_DIARIO['DIA'].dt.day})
DADOS_GERACAO_DIARIO.head()

,DIA,CGH R. Bonito I,CGH R. Bonito II,BC Rio Bonito1,BC Paranoa,BC Aracu1,BC Aracu2,BC Panama1.1,BC Panama1.2,BC Rio Monte1,...,BC Formoso2.3,ARAGUATINS 1.1,ARAGUATINS 1.2,ARAGUATINS 1.3,ARAGUATINS 2.1,ARAGUATINS 2.2,ARAGUATINS 2.3,BC Ibiuna 1.1,BC Ibiuna 1.2,Geração total diária [MWh]
0,2026-01-01,13.29,0,6.518,14.9439,4.0598,7.7737,1.1886,1.5631,3.2764,...,1.26336,6.7858,7.14052,3.62229,5.05026,5.54432,3.63995,0.16386,0.16374,329.96818
1,2026-01-02,11.45,0,6.763,9.4293,2.9414,6.3409,1.0168,1.3317,7.1638,...,0.56766,5.60022,5.82394,2.93867,4.61361,4.95583,3.2818,0,0,358.22481
2,2026-01-03,10.06,0,4.799,12.6727,5.139,8.0415,0.6752,0.8799,5.917,...,3.22545,5.39188,5.47493,2.74141,2.77672,4.02244,2.67815,0,0,309.69146
3,2026-01-04,12.8,0,5.247,9.9107,3.7685,5.1364,0.5193,0.6739,5.4403,...,1.4092,6.55794,6.66382,3.28673,3.90053,5.30417,3.36483,0,0,250.83102
4,2026-01-05,18.69,0,5.196,9.9165,3.1946,4.6,0.9031,1.1849,5.9951,...,1.43179,5.93353,6.03834,3.00125,4.41882,4.61577,3.04802,0,0,276.95887

In [ ]:
MEDIA_GERACAO_DIARIO = pd.read_excel('C:/Users/rafae/Code/Estágio/OM_Dashboard/data-dashboard/src/data/CONTROLE DE Geração 01_2026_JANEIRO.xlsm', sheet_name='2026 P50', header=4, nrows=2)
MEDIA_GERACAO_DIARIO = MEDIA_GERACAO_DIARIO.drop(['DIA'], axis=1).drop([0], axis=0)

In [ ]:
divisor_cleaned = np.where(MEDIA_GERACAO_DIARIO.values == 0, np.nan, MEDIA_GERACAO_DIARIO)
PORCENTAGEM_GERACAO_DIARIA = ((DADOS_GERACAO_DIARIO.iloc[:,1:] / divisor_cleaned) * 100).replace(np.nan, 0)

In [60]:
PORCENTAGEM_GERACAO_DIARIA

,CGH R. Bonito I,CGH R. Bonito II,BC Rio Bonito1,BC Paranoa,BC Aracu1,BC Aracu2,BC Panama1.1,BC Panama1.2,BC Rio Monte1,BC Caiaponia1,...,BC Formoso2.3,ARAGUATINS 1.1,ARAGUATINS 1.2,ARAGUATINS 1.3,ARAGUATINS 2.1,ARAGUATINS 2.2,ARAGUATINS 2.3,BC Ibiuna 1.1,BC Ibiuna 1.2,Geração total diária [MWh]
0,0,0,124.038060,111.537752,88.879802,96.889957,119.283263,118.243289,57.102603,0.000000,...,41.242797,102.835256,108.210853,109.787828,76.504134,83.988428,110.279955,2.126716,2.125158,84.747850
1,0,0,128.700430,70.378076,64.395056,79.031803,102.042085,100.738653,124.853994,127.287486,...,18.531445,84.868410,88.258770,89.068019,69.889518,75.073656,99.429046,0.000000,0.000000,92.005182
2,0,0,91.325353,94.586050,112.506356,100.227766,67.760440,66.561493,103.124192,105.119969,...,105.295861,81.711126,82.969706,83.089275,42.063292,60.934148,81.140197,0.000000,0.000000,79.540050
3,0,0,99.850829,73.971132,82.502472,64.019138,52.114924,50.978282,94.816045,99.677587,...,46.003791,99.382157,100.986713,99.617354,59.087388,80.350503,101.944615,0.000000,0.000000,64.422544
4,0,0,98.880295,74.014422,69.938277,57.333548,90.631596,89.633724,104.485354,102.845197,...,46.741249,89.919549,91.507890,90.964754,66.938731,69.922239,92.346188,0.000000,0.000000,71.133128
5,0,0,98.138122,51.113353,75.597528,52.503820,80.375202,79.292826,96.928375,98.806806,...,119.648052,89.592970,91.078867,90.434347,66.067235,69.458996,89.136513,33.540092,35.217999,64.025617
6,0,0,106.206875,83.795685,86.471610,75.082020,50.087731,48.466813,99.417159,95.060913,...,0.000000,116.235755,118.618796,118.627434,58.742607,120.150904,119.072781,84.686004,87.349784,76.091122
7,0,0,120.232044,93.475442,85.764477,74.256915,69.667206,68.066862,119.127003,110.972807,...,123.973231,55.350973,56.210383,55.868195,41.341009,56.092822,56.733454,79.991941,36.178953,86.959150
8,0,0,105.655003,111.290702,92.868644,82.463091,119.775008,117.796974,101.039748,104.963650,...,138.602580,96.804835,99.349423,98.959953,20.477209,83.397029,84.278069,83.870542,72.820733,102.675020
9,0,0,98.157152,125.603963,124.054732,123.062721,123.859501,121.957540,85.327992,88.065893,...,49.679328,86.070009,86.508428,86.411439,58.078948,90.611679,91.074619,130.087084,113.754101,103.023224
10,0,0,139.319214,137.181755,0.000000,123.249678,129.379087,127.517570,129.608478,125.919938,...,0.000000,76.166406,78.392599,78.673866,58.617025,78.448602,79.411444,21.128281,24.427117,108.867663
11,0,0,79.736034,106.305653,0.000000,50.520827,91.735513,90.087604,87.503064,94.531539,...,114.769535,23.694329,24.463571,1.038991,18.684832,25.791473,26.110047,20.431447,25.785225,85.151600
12,0,0,87.937999,116.308591,68.646610,0.000000,92.949822,91.479502,85.003823,86.515174,...,125.646304,22.071588,22.380588,22.227376,16.252580,21.643799,22.015999,46.636667,47.305468,79.151171
13,0,0,112.467772,119.331415,75.908404,2.450386,99.743930,87.099561,85.155451,90.541098,...,112.122325,73.408594,75.311996,76.074873,73.106768,100.230253,101.085995,68.824023,89.938288,85.686308
14,0,0,99.127686,114.319497,82.723588,82.408250,102.292975,100.973158,114.309777,104.698964,...,154.561247,100.520713,104.080197,104.472849,84.779940,105.973979,106.628548,94.270630,93.322135,93.004412
15,0,0,119.718232,131.220446,119.091667,99.051182,132.369699,130.354319,81.268904,77.068925,...,135.691270,98.057504,100.693322,99.233037,100.216316,101.835848,102.073681,51.327745,38.639615,108.367628
16,0,0,128.262738,141.585376,130.613771,133.111049,85.904824,84.951196,102.573453,75.769466,...,146.450190,59.161263,60.684440,60.744300,59.019825,60.406069,61.419204,49.623622,48.798166,100.832761
17,0,0,138.843462,83.103048,94.335452,77.418985,74.293623,72.076135,125.084050,128.319381,...,117.462774,89.773460,91.954189,92.421402,90.149345,90.909045,91.035233,64.305564,64.724003,86.846581
18,0,0,102.058318,98.044012,90.587429,98.324542,73.912269,73.165447,82.232698,83.097262,...,59.943018,102.946793,105.176017,104.565898,103.925591,105.844459,106.049873,44.942667,44.701260,85.403477
19,0,0,93.038060,74.187581,59.565537,48.418181,101.761088,97.500976,88.318716,87.041671,...,63.683193,89.519168,91.544109,85.446705,94.225366,96.851520,96.581724,85.475248,86.184413,65.275113
20,0,0,61.562308,95.385419,79.398093,68.913678,65.000647,63.384334,54.526677,57.311400,...,119.879181,116.563395,119.972849,120.337163,118.504256,122.132486,122.710555,49.653603,49.895399,76.600580
21,0,0,93.095150,91.021356,63.171257,59.274164,78.036905,75.994632,90.192275,89.189853,...,85.650558,91.989348,92.524301,92.220757,92.898808,93.645177,93.467484,56.053607,55.810902,70.100872
22,0,0,90.602210,72.136539,87.469915,77.133564,96.813532,94.747438,104.673582,101.570673,...,60.241723,54.433218,55.379918,55.486605,54.152898,55.461581,56.059040,91.898095,91.716131,75.656123
23,0,0,110.964395,89.304690,83.894845,81.767610,93.030107,91.592972,108.922640,107.550101,...,142.552664,88.018875,89.058623,88.871617,88.459676,90.524726,91.422733,66.165305,65.816563,84.520437
24,0,0,108.433395,69.752612,71.545198,62.061073,80.495630,79.686188,111.911621,96.399691,...,92.454170,115.692164,115.677312,114.659992,115.241106,118.304144,117.337666,29.330659,28.641612,85.015119
25,0,0,120.821977,114.668801,119.247105,116.004463,100.677242,98.794534,116.882217,115.013117,...,118.338974,88.193606,89.853476,91.282998,88.323793,91.213834,92.742778,107.347348,107.652610,105.756503
26,0,0,77.357274,126.507825,95.235240,100.831015,91.183555,89.489995,58.366166,62.591709,...,153.295261,101.793537,99.272893,101.428011,101.222483,102.803841,103.040158,38.018447,38.426113,100.393935
27,0,0,101.944138,113.125295,76.665890,64.442908,74.313694,73.294046,100.168325,103.517463,...,128.394714,96.554180,97.578925,98.815379,103.342826,105.077639,105.616018,91.512234,90.221097,92.535978
28,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000